// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlraierigswqqbwqwjtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRscmFpZXJpZ3N3cXFid3F3anRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNDc5NTUsImV4cCI6MjA2NjkyMzk1NX0.nblEt_c5OslwiGp_c9HxQ6y_UOcgzuWV56j0AfV79_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});